
import { supabase } from '@/lib/supabase';
import Link from 'next/link';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowRight, BookOpen } from 'lucide-react';
import Image from 'next/image';

export const revalidate = 3600;

async function getArticles() {
  // Fetch published articles
  const { data, error } = await supabase
    .from('articles')
    .select('*')
    .eq('is_published', true)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching articles:', error);
    return [];
  }
  return data;
}

export const metadata = {
  title: 'Conseils Voyage Maroc | Essaouira Travel Services',
  description: 'Guides pratiques, conseils et astuces pour réussir votre voyage au Maroc. Transport, activités, et culture.',
};

export default async function KnowledgeHub() {
  const articles = await getArticles();

  return (
    <div className="min-h-screen bg-black text-white pt-32 pb-24">
      <div className="container mx-auto px-4">
        
        {/* Header */}
        <div className="text-center mb-16">
          <div className="inline-block p-3 rounded-full bg-primary/10 mb-6">
            <BookOpen className="w-8 h-8 text-primary" />
          </div>
          <h1 className="font-headline text-4xl md:text-6xl font-bold mb-6">
             Conseils <span className="text-primary">Voyage</span>
          </h1>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            L'expertise de nos chauffeurs et guides à votre service. 
            Découvrez comment voyager malin entre Marrakech, Essaouira et Agadir.
          </p>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {articles.length > 0 ? (
            articles.map((article) => (
              <Card key={article.id} className="bg-white/5 border-white/10 overflow-hidden hover:border-primary/50 transition-all hover:-translate-y-1">
                {article.cover_image && (
                  <Link href={`/conseils-voyage/${article.slug}`} className="block relative h-48 w-full group-hover:opacity-90 transition-opacity">
                     {/* Replace with Next/Image once you have real URLs */}
                    <Image 
                      src={article.cover_image} 
                      alt={article.title} 
                      fill
                      className="object-cover w-full h-full"
                    />
                  </Link>
                )}
                <CardHeader>
                  <div className="text-xs font-bold text-primary uppercase tracking-widest mb-2">
                    {article.category}
                  </div>
                  <CardTitle className="text-white text-xl line-clamp-2">
                    <Link href={`/conseils-voyage/${article.slug}`} className="hover:text-primary transition-colors">
                        {article.title}
                    </Link>
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-400 text-sm line-clamp-3">
                    {article.excerpt}
                  </p>
                </CardContent>
                <CardFooter>
                  <Link href={`/conseils-voyage/${article.slug}`} className="w-full">
                    <Button variant="outline" className="w-full border-white/20 text-white hover:bg-primary hover:text-black hover:border-primary">
                      Lire l'article <ArrowRight className="w-4 h-4 ml-2" />
                    </Button>
                  </Link>
                </CardFooter>
              </Card>
            ))
          ) : (
            <div className="col-span-full text-center py-20 bg-white/5 rounded-2xl border border-dashed border-white/10">
              <p className="text-gray-500 text-lg">
                Nos guides sont en cours de rédaction par nos experts... Revenez bientôt !
              </p>
               <p className="text-sm text-gray-600 mt-2">
                (This data will be auto-generated by n8n)
              </p>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}
